### ISSUE TITLE
`async` is a keyword in Python 3.7

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/ZEO#104]
```
Python 3.7.0b1+ (heads/3.7:7f38637853, Feb  1 2018, 13:09:53) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ZEO.ClientStorage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/py37/lib/python3.7/site-packages/ZEO/ClientStorage.py", line 271
    self._async = self._server.async
                                   ^
SyntaxError: invalid syntax
```

**Comment by jamadden** [comment]
The commit 52fb9d4 *did not* fix this issue, it just fixed some of the deprecations. There are still some uses in our own code.
