### ISSUE TITLE
Cannot run tests locally

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/ZEO#140]
I tried to run the tests for ZEO locally, both via tox or directly via bin/test after manual buildout, and I get a lot of failures and errors.

On a first glance, there are two categories
- failures on asserts
- time out errors

Examples:
```
(ZEO) jugmac00@jugmac00-XPS-13-9370:~/Projects/ZEO$ bin/test -vv
/home/jugmac00/Projects/ZEO/src/ZEO/tests/testZEO.py:1247: DeprecationWarning: invalid escape sequence \d
  """
Running tests at all levels
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:
 testClientBasics (ZEO.asyncio.tests.ClientTests)

Failure in test testClientBasics (ZEO.asyncio.tests.ClientTests)
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/src/ZEO/asyncio/tests.py", line 311, in testClientBasics
    self.assertEqual(self.pop(), (2, False, 'get_info', ()))
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: [] != (2, False, 'get_info', ())
```

```
Error in test checkQuickVerificationWith2Clients (ZEO.tests.testConnection.FileStorageInvqTests)
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/src/ZEO/tests/ConnectionTests.py", line 598, in checkQuickVerificationWith2Clients
    perstorage = self.openClientStorage(cache="test")
  File "/home/jugmac00/Projects/ZEO/src/ZEO/tests/ConnectionTests.py", line 151, in openClientStorage
    **self._client_options())
  File "/home/jugmac00/Projects/ZEO/src/ZEO/ClientStorage.py", line 281, in __init__
    self._wait()
  File "/home/jugmac00/Projects/ZEO/src/ZEO/asyncio/client.py", line 825, in wait
    self.wait_for_result(self.client.connected, timeout)
  File "/home/jugmac00/Projects/ZEO/src/ZEO/asyncio/client.py", line 759, in wait_for_result
    raise ClientDisconnected("timed out waiting for connection")
ZEO.Exceptions.ClientDisconnected: timed out waiting for connection
```

Complete log -> https://gist.github.com/jugmac00/40b78aee5e0f4c5d64fdab5841937e48

I tried to run the tests both on Ubuntu 18.04 Python 3.6 / 2.7 and Fedora 28 Python 3.6 / 2.7 - no luck.

Does it need something special (like some c extensions or whatever) to get the test suite to run?

I just wonder, as Travis seems to run fine (with an occasional re-run https://github.com/zopefoundation/ZEO/pull/139#issuecomment-486284582 ).

**Comment by mgedmin** [comment]
Tests pass for me on Ubuntu 19.04 if I run `tox -e py27`.

I'm seeing failures with `tox -e py35/py36/py37`: 1 test failed in the UnitTests layer, specifically

```
Error in test test_client_side (ZEO.tests.test_client_side_conflict_resolution.ClientSideConflictResolutionTests)
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.5/unittest/case.py", line 601, in run
    testMethod()
  File "/home/mg/src/zopefoundation/ZEO/.tox/py35/lib/python3.5/site-packages/ZEO/tests/test_client_side_conflict_resolution.py", line 114, in test_client_side
    addr, stop = ZEO.server('data.fs', threaded=False)
  File "/home/mg/src/zopefoundation/ZEO/.tox/py35/lib/python3.5/site-packages/ZEO/__init__.py", line 90, in server
    blob_dir=blob_dir, suicide=False, threaded=threaded, **kw)
  File "/home/mg/src/zopefoundation/ZEO/.tox/py35/lib/python3.5/site-packages/ZEO/_forker.py", line 245, in start_zeo_server
    addr = qout.get(timeout=start_timeout)
  File "/home/mg/src/zopefoundation/ZEO/.tox/py35/lib/python3.5/site-packages/ZEO/_forker.py", line 292, in get
    raise Empty()
queue.Empty
```

This is preceded by a

```
SERVER FAILED TO START
Exit status 0
```

and a whole bunch of ResourceWarnings.

I think it's just the usual non-deterministic test failure fun, that happens to trigger rarely on Travis but we've been blessed with faster/slower machines that make the failures happen much more often.

**Comment by jugmac00** [comment]
`tox -e py27` on Ubuntu 18.04

```
jugmac00@jugmac00-XPS-13-9370:~/Projects/ZEO$ tox -e=py27
GLOB sdist-make: /home/jugmac00/Projects/ZEO/setup.py
py27 inst-nodeps: /home/jugmac00/Projects/ZEO/.tox/.tmp/package/1/ZEO-5.2.2.dev0.zip
py27 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,BTrees==4.5.1,funcsigs==1.0.2,futures==3.2.0,manuel==1.10.1,mock==2.0.0,msgpack==0.6.1,pbr==5.1.3,persistent==4.4.3,random2==1.0.1,six==1.12.0,transaction==2.4.0,trollius==2.2,zc.lockfile==1.4,ZConfig==3.4.0,zdaemon==4.3,ZEO==5.2.2.dev0,ZODB==5.5.1,zodbpickle==1.0.3,zope.exceptions==4.3,zope.interface==4.6.0,zope.testing==4.7,zope.testrunner==5.0,ZopeUndo==4.3
py27 run-test-pre: PYTHONHASHSEED='1728809933'
py27 run-test: commands[0] | zope-testrunner -u --test-path=src --auto-color --auto-progress
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:
    1/96 (1.0%)

Failure in test testClientBasics (ZEO.asyncio.tests.ClientTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 311, in testClientBasics
    self.assertEqual(self.pop(), (2, False, 'get_info', ()))
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: [] != (2, False, 'get_info', ())

    4/96 (4.2%)

Failure in test test_bad_server_tid (ZEO.asyncio.tests.ClientTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 462, in test_bad_server_tid
    self.assertEqual(self.pop(), (3, False, 'get_info', ()))
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: [] != (3, False, 'get_info', ())

    5/96 (5.2%)

Failure in test test_cache_behind (ZEO.asyncio.tests.ClientTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 347, in test_cache_behind
    self.assertEqual(self.pop(), (3, False, 'getInvalidations', (b'a'*8, )))
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: [] != (3, False, 'getInvalidations', ('aaaaaaaa',))

    6/96 (6.2%)

Failure in test test_cache_way_behind (ZEO.asyncio.tests.ClientTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 382, in test_cache_way_behind
    self.assertEqual(self.pop(), (3, False, 'getInvalidations', (b'a'*8, )))
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: [] != (3, False, 'getInvalidations', ('aaaaaaaa',))

    12/96 (12.5%)

Failure in test test_invalidations_while_verifying (ZEO.asyncio.tests.ClientTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 570, in test_invalidations_while_verifying
    no_output=False)
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 65, in send
    target.assert_called_with(*args)
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: invalidateTransaction('eeeeeeee', ['11111111'])
Not called

    17/96 (17.7%)/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/marshal.py:69: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  return unpackb(data, encoding='utf-8', use_list=False)


Failure in test testClientBasics (ZEO.asyncio.tests.MsgpackClientTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 311, in testClientBasics
    self.assertEqual(self.pop(), (2, False, 'get_info', ()))
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: [] != (2, False, 'get_info', ())

    20/96 (20.8%)

Failure in test test_bad_server_tid (ZEO.asyncio.tests.MsgpackClientTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 462, in test_bad_server_tid
    self.assertEqual(self.pop(), (3, False, 'get_info', ()))
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: [] != (3, False, 'get_info', ())

    21/96 (21.9%)

Failure in test test_cache_behind (ZEO.asyncio.tests.MsgpackClientTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 347, in test_cache_behind
    self.assertEqual(self.pop(), (3, False, 'getInvalidations', (b'a'*8, )))
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: [] != (3, False, 'getInvalidations', ('aaaaaaaa',))

    22/96 (22.9%)

Failure in test test_cache_way_behind (ZEO.asyncio.tests.MsgpackClientTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 382, in test_cache_way_behind
    self.assertEqual(self.pop(), (3, False, 'getInvalidations', (b'a'*8, )))
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: [] != (3, False, 'getInvalidations', ('aaaaaaaa',))

    28/96 (29.2%)

Failure in test test_invalidations_while_verifying (ZEO.asyncio.tests.MsgpackClientTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 570, in test_invalidations_while_verifying
    no_output=False)
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/asyncio/tests.py", line 65, in send
    target.assert_called_with(*args)
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: invalidateTransaction('eeeeeeee', ('11111111',))
Not called

    91/96 (94.8%)

Failure in test kill_does_not_cause_cache_corruption (ZEO.tests.test_cache)
Failed doctest test for ZEO.tests.test_cache.kill_does_not_cause_cache_corruption
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/tests/test_cache.py", line 359, in kill_does_not_cause_cache_corruption

----------------------------------------------------------------------
File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/tests/test_cache.py", line 394, in ZEO.tests.test_cache.kill_does_not_cause_cache_corruption
Failed example:
    for i in range(10):
        _ = os.spawnl(os.P_WAIT, sys.executable, sys.executable, 't')
        if os.path.exists('cache'):
            cache = ZEO.cache.ClientCache('cache')
            cache.close()
            os.remove('cache')
            os.remove('cache.lock')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest ZEO.tests.test_cache.kill_does_not_cause_cache_corruption[2]>", line 2, in <module>
        _ = os.spawnl(os.P_WAIT, sys.executable, sys.executable, 't')
      File "/home/jugmac00/Projects/ZEO/.tox/py27/lib/python2.7/os.py", line 610, in spawnl
        return spawnv(mode, file, args)
      File "/home/jugmac00/Projects/ZEO/.tox/py27/lib/python2.7/os.py", line 565, in spawnv
        return _spawnvef(mode, file, args, None, execv)
      File "/home/jugmac00/Projects/ZEO/.tox/py27/lib/python2.7/os.py", line 548, in _spawnvef
        wpid, sts = waitpid(pid, 0)
    OSError: [Errno 4] Interrupted system call

    92/96 (95.8%)Traceback (most recent call last):
  File "t", line 15, in <module>
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/ZEO/cache.py", line 194, in __init__
    self._lock_file = zc.lockfile.LockFile(path + '.lock')
  File "/home/jugmac00/Projects/ZEO/.tox/py27/local/lib/python2.7/site-packages/zc/lockfile/__init__.py", line 85, in __init__
    fp = open(path, 'a+')
IOError: [Errno 2] No such file or directory: 'cache.lock'
                  
  Ran 96 tests with 11 failures, 0 errors and 0 skipped in 5.761 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
ERROR: InvocationError for command /home/jugmac00/Projects/ZEO/.tox/py27/bin/zope-testrunner -u --test-path=src --auto-color --auto-progress (exited with code 1)
_________________________________________________________________________________________________ summary __________________________________________________________________________________________________
ERROR:   py27: commands failed
```

**Comment by jugmac00** [comment]
@mgedmin Thank you, once again.

Those flaky tests are really a pity and sadly spoil any motivation to work on this project :-(

**Comment by mgedmin** [comment]
> Those flaky tests are really a pity and sadly spoil any motivation to work on this project :-(

Unless you enjoy hunting down and fixing flaky tests, of course ;)

------

I can only try to figure out the failure I can reproduce.  Exporting `ZEO_TEST_SERVER_DEBUG=1` before running the failing test case gives me this interesting tidbit:

```
In server thread
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/ZEO/src/ZEO/_forker.py", line 119, in runner
    server.open_storages()
  File "/home/mg/src/zopefoundation/ZEO/src/ZEO/runzeo.py", line 205, in open_storages
    self.storages[opener.name] = opener.open()
  File "/home/mg/.cache/buildout/eggs/ZODB-5.5.1-py3.7.egg/ZODB/config.py", line 207, in open
    return FileStorage(config.path, **options)
  File "/home/mg/.cache/buildout/eggs/ZODB-5.5.1-py3.7.egg/ZODB/FileStorage/FileStorage.py", line 306, in __init__
    read_only=read_only,
  File "/home/mg/.cache/buildout/eggs/ZODB-5.5.1-py3.7.egg/ZODB/FileStorage/FileStorage.py", line 1619, in read_index
    raise FileStorageFormatError(name)
ZODB.FileStorage.FileStorage.FileStorageFormatError: data.fs
```

And I see a `data.fs` file in the current working directory (BAD TEST!  SHOULD'VE USED A TEMPORARY DIRECTORY!  NO COOKIE!), and if I `rm data.fs*` and re-run ... I get the same error.

Hmm.  Oh because unlike `tox`, `bin/test` does a `os.chdir("parts/test")` and so I need to rm parts/test/data.fs*.  And now the test succeeds.

I'll prepare a patch to make it use a temporary directory.

**Comment by mgedmin** [comment]
Unfortunately I cannot reproduce your failures, so I'm not sure what to do there.  Would it help if I shared my techniques for dealing with flaky tests?

First, it's very helpful to be able to reproduce the failure quickly and to avoid distractions from other tests.  `bin/test -m ZEO.asyncio.tests -t testClientBasics.*tests.ClientTests` in this case.

Next it sometimes helps to strace the test to see what's happening on a macro level. `strace -o /tmp/trace.log -f -s 1024 bin/test -m ZEO.asyncio.tests -t testClientBasics.*tests.ClientTests`.  I've a Python script [`strace-project-tree`](https://github.com/mgedmin/scripts/blob/master/strace-process-tree) that shows me what threads/subprocesses appear in an strace log.  For this particular test there are none.

Finally there's nothing to it but to read the source code for the test and any metthods/functions it invokes, to understand what's happening.  Then maybe add some debug prints?

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2019-4-25 02:33 -0700:
>I tried to run the tests for ZEO locally, both via tox or directly via bin/test after manual buildout, and I get a lot of failures and errors.
>
>On a first glance, there are two categories
>- failures on asserts
>- time out errors
> ...
>I tried to run the tests both on Ubuntu 18.04 Python 3.6 / 2.7 and Fedora 28 Python 3.6 / 2.7 - no luck.

I ran the ZEO test suite under Ubuntu 18.04 Python 3.6
with "[dm.zopepatches.]ztest" (a tiny wrapper around "zope.testrunner").


All SSL tests failed -- maybe due to
"Error: no values for 'authenticate'; 1 required
(line 7 in file:///tmp/tmp8i2rz1k3/conf)".

All those failing SSL tests failed with
"ZEO.Exceptions.ClientDisconnected: timed out waiting for connection".
Apparently, this error occurs whenever the ZEO server did not
start successfully.

I will look for a way to reliably get information about a
failing ZEO start and its reason -- maybe, it is sufficient to
set "server_debug = True" in the corresponding test class
(this activates debug logging in the ZEO server).


Apart from the SSL tests, only two tests failed:
Tests with failures:
   quick_close_doesnt_kill_server (ZEO.tests.testZEO)
   runzeo_without_configfile (ZEO.tests.testZEO)

**Comment by d-maurer** [comment]
Dieter Maurer wrote at 2019-4-25 15:49 +0200:
>Jürgen Gmach wrote at 2019-4-25 02:33 -0700:
>>I tried to run the tests for ZEO locally, both via tox or directly via bin/test after manual buildout, and I get a lot of failures and errors.
> ...
>I ran the ZEO test suite under Ubuntu 18.04 Python 3.6
>with "[dm.zopepatches.]ztest" (a tiny wrapper around "zope.testrunner").
>
>
>All SSL tests failed -- maybe due to
>"Error: no values for 'authenticate'; 1 required
>(line 7 in file:///tmp/tmp8i2rz1k3/conf)".

> ...
>I will look for a way to reliably get information about a
>failing ZEO start and its reason -- maybe, it is sufficient to
>set "server_debug = True" in the corresponding test class
>(this activates debug logging in the ZEO server).

When the ZEO server has debug logging activated, it produces
the following output:
(11880) opening storage '1' using MappingStorage
StorageServer created RW with storages: 1:RW:Mapping Storage
listening on ('127.0.0.1', 0)
SERVER CREATED
ADDRESS SENT
[('127.0.0.1', 40083)] ClientStorage (pid=11880) created RW/normal for storage: '1'
created temporary cache file 7
disconnected <ZEO.asyncio.client.Client object at 0xb5d642cc> None
try_connecting
Accepted connection
Connected Protocol(('127.0.0.1', 40083), '1', False)
connection_lost None
Stopping client thread
[('127.0.0.1', 40083)] ClientStorage (pid=11880) created RW/normal for storage: '1'
created temporary cache file 7
disconnected <ZEO.asyncio.client.Client object at 0xb541d20c> None
try_connecting
Accepted connection
Connection to ('127.0.0.1', 40083) failed, retrying, [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)
Accepted connection
Connection to ('127.0.0.1', 40083) failed, retrying, [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)
...
Connection to ('127.0.0.1', 40083) failed, retrying, [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)
Stopping client thread


Apparently, something is wrong with the certificate verification.

**Comment by d-maurer** [comment]
Dieter Maurer wrote at 2019-4-25 16:31 +0200:
> ...
>Apparently, something is wrong with the certificate verification.

The SSL errors occur only with Python 3.6, not with Python 2.7.
Will try to find out why.

**Comment by jugmac00** [comment]
**Update**
Rebased to #141 now Fedora 28 / Python 2.7 is green all the time.

```
Total: 911 tests, 0 failures, 0 errors and 0 skipped in 7 minutes 41.775 seconds.
___________________________________________________________________________________ summary ____________________________________________________________________________________
  py27: commands succeeded
  congratulations :)


Total: 911 tests, 0 failures, 0 errors and 0 skipped in 43 minutes 20.128 seconds.
______________________________________________________________________ summary ______________________________________________________________________
  py27: commands succeeded
  congratulations :)
```

Times vary, though oO

**Comment by mgedmin** [comment]
> 43 minutes

O.o

**Comment by jugmac00** [comment]
> Unfortunately I cannot reproduce your failures, so I'm not sure what to do there. Would it help if I shared my techniques for dealing with flaky tests?
@mgedmin Thank you very much! I really appreciate your support!

Coming from a backround with pytest only, one assert statement per test, largest test suite takes takes 90 seconds, Python 2.7 only, no funky concurreny/threading, no tox, no zope.test-runner... this helps me get going with the Zope ecosystem.

>The SSL errors occur only with Python 3.6, not with Python 2.7.
Will try to find out why.
@d-maurer Thank you very much!

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2019-4-25 22:01 +0000:
> ...
>>The SSL errors occur only with Python 3.6, not with Python 2.7.
>Will try to find out why.

The provided test certificates are wrong:
For certificate verification, OpenSSL (and therefore Python)
silently ignores certificates without the X509v3 extension "CA:TRUE".
The test certificates are version 1 certificates (and therefore
lack the version 3 extension). Therefore, their verification fails.

I will provide a PR with proper test certificates.

**Comment by mgedmin** [comment]
Very interesting!  How come I don't see those failures?  Python 3.7.3, OpenSSL 1.1.1b-1ubuntu2.

**Comment by mgedmin** [comment]
> Very interesting! How come I don't see those failures? Python 3.7.3, OpenSSL 1.1.1b-1ubuntu2.

Oh, never mind!  It's because tox was running only _unit_ tests and stopping, because of that other failure, so I never actually saw how the other test layers behave!

**Comment by jugmac00** [comment]
With #145 ...

```
  py27: commands succeeded
  py36: commands succeeded
  congratulations :)
```

@d-maurer + @mgedmin 
Awesome!

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2019-4-26 18:42 +0000:
>  congratulations :)

Thank you for initially taking up the task!

**Comment by mgedmin** [comment]
:100:
