### ISSUE TITLE
"ValueError: Attempted relative import in non-package" - In windows 

### ISSUE THREAD

**Issue by fazalsulaiman** [zopefoundation/ZEO#163]
**System Details**
> **OS:** Windows server 2016 data center (64bit)
> **Python version:** 2.7.18 (32bit)
> **ZEO:** 5.2.1
> **zc.buildout:** 2.13.3
> **setuptools:** 44.0.0

While running ZEO as a service in windows, we are getting "ValueError: Attempted relative import in non-package" error

**Error Message from Event Viewer**
```
ZEO_-719346442 (ZEO instance at D:\work\zope4\modules\zeo_build\parts\zeo_server1): Process terminated with exit code 1.
Traceback (most recent call last):
  File "d:\work\zope4\modules\zeo_build\eggs\zeo-5.2.1-py2.7.egg\\ZEO\\runzeo.py", line 399, in <module>
    main()
  File "d:\work\zope4\modules\zeo_build\eggs\zeo-5.2.1-py2.7.egg\\ZEO\\runzeo.py", line 390, in main
    s.main()
  File "d:\work\zope4\modules\zeo_build\eggs\zeo-5.2.1-py2.7.egg\\ZEO\\runzeo.py", line 153, in main
    self.create_server()
  File "d:\work\zope4\modules\zeo_build\eggs\zeo-5.2.1-py2.7.egg\\ZEO\\runzeo.py", line 249, in create_server
    self.server = create_server(self.storages, self.options)
  File "d:\work\zope4\modules\zeo_build\eggs\zeo-5.2.1-py2.7.egg\\ZEO\\runzeo.py", line 343, in create_server
    from .StorageServer import StorageServer
ValueError: Attempted relative import in non-package
```

**Comment by dataflake** [comment]
You seem to be using the `runzeo` script inside the egg directly. You should be using the console script `runzeo` that will be created when you install the ZEO egg in your virtual environment or your zc.buildout-driven sandbox instead.

**Comment by fazalsulaiman** [comment]
Thanks dataflake. Working fine now, after using console script.
