### ISSUE TITLE
Pickling in marshal.py is not compatible with PyPy 5.0

### ISSUE THREAD

**Issue by michwill** [zopefoundation/ZEO#17]
Tried to run ZEO client/server with PyPy 5.0, getting the following error:

```
Traceback (most recent call last):
  File "/home/michwill/Projects/zerodb-server/.venvpypy/site-packages/ZEO/zrpc/client.py", line 600, in test_connection
    self.preferred = self.client.testConnection(self.conn)
  File "/home/michwill/Projects/zerodb-server/.venvpypy/site-packages/ZEO/ClientStorage.py", line 575, in testConnection
    auth = stub.getAuthProtocol()
  File "/home/michwill/Projects/zerodb-server/.venvpypy/site-packages/ZEO/ServerStub.py", line 81, in getAuthProtocol
    return self.rpc.call('getAuthProtocol')
  File "/home/michwill/Projects/zerodb-server/.venvpypy/site-packages/ZEO/zrpc/connection.py", line 775, in call
    msgid = self.send_call(method, args)
  File "/home/michwill/Projects/zerodb-server/.venvpypy/site-packages/ZEO/zrpc/connection.py", line 552, in send_call
    buf = self.encode(msgid, async, method, args)
  File "/home/michwill/Projects/zerodb-server/.venvpypy/site-packages/ZEO/zrpc/marshal.py", line 44, in encode
    return pickler.dump(args, 1)
TypeError: dump() takes exactly 2 arguments (3 given)
```

Can't we use zodbpickle here?

**Comment by jamadden** [comment]
You seem to be running an outdated version of ZEO. Version 4.2.0b1 or higher is required for (any) PyPy support. I just ran the unit and functional tests of master (which is unchanged from 4.2.0b1) on PyPy 5.0.0 and they pass with flying colors.

marshal.py in 4.2.0b1 has these lines in the `encode` method:
```python
        pickler = Pickler(1)
        pickler.fast = 1
        # Only CPython's cPickle supports dumping
        # and returning in one operation:
        #   return pickler.dump(args, 1)
        # For PyPy we must return the value; fortunately this
        # works the same on CPython and is no more expensive
        pickler.dump(args)
        return pickler.getvalue()
```

**Comment by michwill** [comment]
You're right. With 4.2.0b1 works indeed. Thank you!
