### ISSUE TITLE
Python 3.12 test failures

### ISSUE THREAD

**Issue by jamesjer** [zopefoundation/ZEO#231]
## BUG/PROBLEM REPORT

The Fedora Linux distribution has rebuilt all of its python packages with python 3.12 beta 4, to find problems prior to the python 3.12 release.  The ZEO package has many failing tests.  The first is:

```
Failure in test testClientBasics (ZEO.asyncio.tests.ClientTests.testClientBasics)
Traceback (most recent call last):
  File "/usr/lib64/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib64/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/usr/lib64/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
  File "/builddir/build/BUILDROOT/python-ZEO-5.4.1-1.fc39.x86_64/usr/lib64/python3.12/site-packages/ZEO/asyncio/tests.py", line 280, in testClientBasics
    self.assertEqual(self.pop(), (4, False, 'foo', (1, 2)))
  File "/usr/lib64/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.12/unittest/case.py", line 878, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: [] != (4, False, 'foo', (1, 2))
```

Most of the rest get `None` back from `self._task.cancelling()`, like this:
```
Error in test testClientBasics (ZEO.asyncio.tests.ClientTests.testClientBasics)
Traceback (most recent call last):
  File "/usr/lib64/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib64/python3.12/unittest/case.py", line 637, in run
    self._callTearDown()
  File "/usr/lib64/python3.12/unittest/case.py", line 594, in _callTearDown
    self.tearDown()
  File "/builddir/build/BUILDROOT/python-ZEO-5.4.1-1.fc39.x86_64/usr/lib64/python3.12/site-packages/ZEO/asyncio/tests.py", line 109, in tearDown
    self.close()
  File "/builddir/build/BUILDROOT/python-ZEO-5.4.1-1.fc39.x86_64/usr/lib64/python3.12/site-packages/ZEO/asyncio/client.py", line 1063, in close
    super(ClientThread, self).close()
  File "/builddir/build/BUILDROOT/python-ZEO-5.4.1-1.fc39.x86_64/usr/lib64/python3.12/site-packages/ZEO/asyncio/client.py", line 967, in close
    call(self.client.close_co())
  File "/builddir/build/BUILDROOT/python-ZEO-5.4.1-1.fc39.x86_64/usr/lib64/python3.12/site-packages/ZEO/asyncio/client.py", line 862, in io_call
    return future.result() if wait else future
  File "_futures.pyx", line 206, in ZEO.asyncio._futures.ConcurrentFuture.result
  File "_futures.pyx", line 216, in ZEO.asyncio._futures.ConcurrentFuture.result
  File "_futures.pyx", line 77, in ZEO.asyncio._futures.Future.result
  File "_futures.pyx", line 278, in ZEO.asyncio._futures.CoroutineExecutor.step
  File "/builddir/build/BUILDROOT/python-ZEO-5.4.1-1.fc39.x86_64/usr/lib64/python3.12/site-packages/ZEO/asyncio/client.py", line 728, in close_co
    yield asyncio.wait_for(asyncio.shield(closing), 10)
  File "_futures.pyx", line 264, in ZEO.asyncio._futures.CoroutineExecutor.step
  File "_futures.pyx", line 70, in ZEO.asyncio._futures.Future.result
  File "_futures.pyx", line 77, in ZEO.asyncio._futures.Future.result
  File "_futures.pyx", line 276, in ZEO.asyncio._futures.CoroutineExecutor.step
  File "/usr/lib64/python3.12/asyncio/tasks.py", line 509, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/lib64/python3.12/asyncio/timeouts.py", line 87, in __aenter__
    self._cancelling = self._task.cancelling()
AttributeError: 'NoneType' object has no attribute 'cancelling'
The following test left new threads behind:
testClientBasics (ZEO.asyncio.tests.ClientTests.testClientBasics)
New thread(s): [<Thread(__name__ zeo client networking thread, started daemon 140417319212736)>]
```

One that looks different from the above:
```
Failure in test test_close_with_stopped_loop (ZEO.asyncio.tests.ClientTests.test_close_with_stopped_loop)
Traceback (most recent call last):
  File "/usr/lib64/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib64/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/usr/lib64/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
  File "/builddir/build/BUILDROOT/python-ZEO-5.4.1-1.fc39.x86_64/usr/lib64/python3.12/site-packages/ZEO/asyncio/tests.py", line 937, in test_close_with_stopped_loop
    self.assertTrue(loop.is_closed())
  File "/usr/lib64/python3.12/unittest/case.py", line 727, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
```

There are a number of [changes to asyncio](https://docs.python.org/3.12/whatsnew/3.12.html#asyncio) in python 3.12.

### What version of Python and Zope/Addons I am using:

Fedora Rawhide (which will become Fedora 39 in the fall)
Python 3.12 beta 4
BTrees 5.0
persistent 5.0
ZConfig 4.0
zdaemon 4.2.0
ZODB 5.8.1
zodbpickle 3.0.1
zope.exceptions 4.0.8
zope.interface 5.5.2
zope.testing 5.0.1
zope.testrunner 6.0

**Comment by jamesjer** [comment]
Thank you!

**Comment by d-maurer** [comment]
Jerry James wrote at 2023-8-1 12:35 -0700:
>Thank you!

You are welcome -- and thank you for your problem report!
