### ISSUE TITLE
Can a persistent cache file be shared by various instances?

### ISSUE THREAD

**Issue by hvelarde** [zopefoundation/ZEO#95]
I was trying to set only one persistent cache file among 2 instances but I got a lot of `LogError` exceptions when I tried to start the second one.

I just want to know if this is possible or not:

```
2017-08-30T19:28:50 ERROR zc.lockfile Error locking file /tmp/zeoclient-1.zec.lock; pid=10889
Traceback (most recent call last):
  File "/opt/plone/buildout/eggs/zc.lockfile-1.0.2-py2.7.egg/zc/lockfile/__init__.py", line 84, in __init__
    _lock_file(fp)
  File "/opt/plone/buildout/eggs/zc.lockfile-1.0.2-py2.7.egg/zc/lockfile/__init__.py", line 59, in _lock_file
    raise LockError("Couldn't lock %r" % file.name)
LockError: Couldn't lock '/tmp/zeoclient-1.zec.lock'
```

**Comment by jimfulton** [comment]
Nope.  A ZEO client cache can only be used by a single process at a time.

**Comment by jamadden** [comment]
FWIW, RelStorage supports a [`cache-local-dir` option](http://relstorage.readthedocs.io/en/latest/relstorage-options.html#persistent-local-caching) that allows multiple instances to share the same cache *directory*. It's **far** from perfect (see https://github.com/zopefoundation/ZODB/issues/163 for one), but it may be helpful to some.

**Comment by hvelarde** [comment]
thanks!
