### ISSUE TITLE
conflict resolution logs coming continuously in zeo.log

### ISSUE THREAD

**Issue by sanjay-raojjn** [zopefoundation/ZEO#98]
I am getting following logs in zeo.log again and again :

2017-06-09T15:31:46 ERROR ZODB.ConflictResolution Unexpected error while trying to resolve conflict on <type 'BTrees.OOBTree.OOBucket'>
Traceback (most recent call last):
File "C:\batonSites\Python27\lib\site-packages\zodb-4.4.3-py2.7.egg\ZODB\ConflictResolution.py", line 285, in tryToResolveConflict
resolved = resolve(old, committed, newstate)
File "C:\batonSites\Python27\lib\site-packages\zodb-4.4.3-py2.7.egg\ZODB\ConflictResolution.py", line 178, in _cmp_
"can't reliably compare against different "
ValueError: can't reliably compare against different PersistentReferences

What could be the reason of getting this type of error at ZEO end ?

**Comment by azmeuk** [comment]
It looks like there are concurrent transactions trying to write different persistent objects on the same key of your OOBTree. During the conflict resolution phase, the server have to work with PersistentReferences of your objects, but it cannot solve conflicts on different PersistentReferences, as [the code shows](https://github.com/zopefoundation/ZODB/blob/master/src/ZODB/ConflictResolution.py#L175).

Maybe you can try to update your existing objects in your OOBTree instead of creating new ones.
